apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: moodle
message: |-
  The following service(s) have been created in your project: ${DATABASE_SERVICE_NAME}.

         Username: ${MYSQL_USER}
         Password: ${MYSQL_PASSWORD}
    Database Name: ${MYSQL_DATABASE}
   Connection URL: mysql://${DATABASE_SERVICE_NAME}:3306/

  For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/5.7/root/usr/share/container-scripts/mysql/README.md.
metadata:
  annotations:
    description: |-
      MySQL database service, with persistent storage. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/5.7/root/usr/share/container-scripts/mysql/README.md.

      NOTE: Scaling to more than one replica is not supported. You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-mysql-database
    openshift.io/display-name: MySQL
    openshift.io/documentation-url: https://docs.openshift.org/latest/using_images/db_images/mysql.html
    openshift.io/long-description: This template provides a standalone MySQL server
      with a database created.  The database is stored on persistent storage.  The
      database name, username, and password are chosen via parameters when provisioning
      this service.
    openshift.io/provider-display-name: Red Hat, Inc.
    openshift.io/support-url: https://access.redhat.com
    tags: database,mysql
  name: mysql-persistent
objects:

# ================
# Secret Mysql
# =================
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: ${DATABASE_SERVICE_NAME}
  stringData:
    database-name: ${MYSQL_DATABASE}
    database-password: ${MYSQL_PASSWORD}
    database-root-password: ${MYSQL_ROOT_PASSWORD}
    database-user: ${MYSQL_USER}
# ================
# Service Mysql
# =================
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: mysql
      port: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}

# ================
# PVC Mysql
# =================      
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}

# ================
# DC Mysql
# =================
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: ${DATABASE_SERVICE_NAME}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ${DATABASE_SERVICE_NAME}-data
        volumes:
        - name: ${DATABASE_SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: ${DATABASE_SERVICE_NAME}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:${MYSQL_VERSION}
          namespace: ${NAMESPACE}
      type: ImageChange
    - type: ConfigChange

# ================
# PVCs moodle
# =================
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: behatdata
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 3Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: behatfaildumps
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 4Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: moodledata3
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 5Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: phpunitdata
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 4Gi

# ===============
# Image Streams Moodle
# ===============

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
    generation: 2
    labels:
      app: moodle2
    name: moodle2
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: lasher/moodle
      from:
        kind: DockerImage
        name: lasher/moodle
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source


# ======================
# Config Map Moodle
# ======================

- apiVersion: v1
  data:
    config.php: |-
      <?php  // Moodle configuration file

      unset($CFG);
      global $CFG;
      $CFG = new stdClass();

      $CFG->dbtype    = 'mysqli';
      $CFG->dblibrary = 'native';
      $CFG->dbhost    = 'mysql';
      $CFG->dbname    = 'moodle';
      $CFG->dbuser    = 'moodle';
      $CFG->dbpass    = 'moodle';
      $CFG->prefix    = 'mdl_';
      $CFG->dboptions = array (
        'dbpersist' => 0,
        'dbport' => 3306,
        'dbsocket' => '',
        'dbcollation' => 'utf8mb4_general_ci',
      );

      $CFG->wwwroot   = getenv('URLMOODLE');
      $CFG->dataroot  = '/var/www/moodledata';
      $CFG->admin     = 'admin';

      $CFG->directorypermissions = 0777;

      require_once('/var/www/html/lib/setup.php');

      // There is no php closing tag in this file,
      // it is intentional because it prevents trailing whitespace problems!
  kind: ConfigMap
  metadata:
    name: config

# ======================
# DeploymentCF Moodle
# ======================

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 21
    labels:
      app: moodle2
    name: moodle2
  spec:
    replicas: 1
    selector:
      app: moodle2
      deploymentconfig: moodle2
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: moodle2
          deploymentconfig: moodle2
      spec:
        containers:
        - image: docker.io/lasher/moodle
          imagePullPolicy: Always
          name: moodle2
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/www/moodledata
            name: volume-3as5g
          - mountPath: /var/www/behatdata
            name: volume-2p9ug
          - mountPath: /var/www/behatfaildumps
            name: volume-p086a
          - mountPath: /var/www/phpunitdata
            name: volume-i8rq0
          - mountPath: /config
            name: config-3fr50
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-3as5g
          persistentVolumeClaim:
            claimName: moodledata3
        - name: volume-2p9ug
          persistentVolumeClaim:
            claimName: behatdata
        - name: volume-p086a
          persistentVolumeClaim:
            claimName: behatfaildumps
        - name: volume-i8rq0
          persistentVolumeClaim:
            claimName: phpunitdata
        - configMap:
            defaultMode: 420
            name: config
          name: config-3fr50
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - moodle2
        from:
          kind: ImageStreamTag
          name: moodle2:latest
      type: ImageChange

# ======================
# Service Moodle
# ======================

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: moodle2
    name: moodle2
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: moodle2
    sessionAffinity: None
    type: ClusterIP

# ======================
# Route Moodle
# ======================
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: moodle2
    name: moodle2
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: moodle2
      weight: 100
    wildcardPolicy: None



# ======================
# Service Memcached
# ======================
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: memcached
    name: memcached
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: memcached
      from:
        kind: DockerImage
        name: memcached
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source


- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    generation: 2
    labels:
      app: memcached
    name: memcached
  spec:
    replicas: 1
    selector:
      app: memcached
      deploymentconfig: memcached
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: memcached
          deploymentconfig: memcached
      spec:
        containers:
        - image: memcached@sha256:553577cfa46656a9df0ddc651584e1d360f8da050b3583e7809a2ce146ab9036
          imagePullPolicy: Always
          name: memcached
          ports:
          - containerPort: 11211
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - memcached
        from:
          kind: ImageStreamTag
          name: memcached:latest
        lastTriggeredImage: memcached@sha256:553577cfa46656a9df0ddc651584e1d360f8da050b3583e7809a2ce146ab9036
      type: ImageChange
  
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: memcached
    name: memcached
  spec:
    ports:
    - name: 11211-tcp
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      deploymentconfig: memcached
    sessionAffinity: None
    type: ClusterIP


parameters:
# Moodle
- description: Dados que precisem ser personalizados
  displayName: Dado Personalizado Qualquer
  name: DADOPERSONALIZADO
  value: Qualquer dado
# Mysql  
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  value: openshift
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql
- description: Username for MySQL user that will be used for accessing the database.
  displayName: MySQL Connection Username
  value: moodle
  name: MYSQL_USER
  required: true
- description: Password for the MySQL connection user.
  displayName: MySQL Connection Password
  value: moodle
  name: MYSQL_PASSWORD
  required: true
- description: Password for the MySQL root user.
  displayName: MySQL root user Password
  value: moodle
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Name of the MySQL database accessed.
  displayName: MySQL Database Name
  name: MYSQL_DATABASE
  required: true
  value: moodle
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Version of MySQL image to be used (5.7, or latest).
  displayName: Version of MySQL Image
  name: MYSQL_VERSION
  required: true
  value: "5.7"